{{- if and .Values.qdrant.apiKey (not .Values.qdrant.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qdrant.fullname" . }}
  labels:
    {{- include "qdrant.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.qdrant.apiKey | b64enc | quote }}
{{- end }}
