{{- if and .Values.namespace .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name | default .Release.Namespace }}
  labels:
    {{- include "neio-leasingops.labels" . | nindent 4 }}
    app.kubernetes.io/component: namespace
  {{- with .Values.namespace.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
