apiVersion: v1
kind: Service
metadata:
  name: {{ include "neio-leasingops.fullname" . }}-app
  namespace: {{ ((.Values.namespace).name) | default .Release.Namespace }}
  labels:
    {{- include "neio-leasingops.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
  {{- with .Values.app.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.app.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.app.service.port | default 80 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "neio-leasingops.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: app
